on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/**'
      - 'FiraCode.glyphs'
      - 'script/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    container: tonsky/firacode:latest
    steps:
    - uses: actions/checkout@v2
    - if: startsWith(github.ref, 'refs/tags/')
      run: python3 ./script/update_version.py
    - run: ./script/build.sh
    - run: echo "hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: Fira_Code_${{ env.hash }}
        path: distr
    - if: startsWith(github.ref, 'refs/tags/')
      run: python3 ./script/release.py
